2024-12-14 15:23:00,107 - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/home/sergey/Документы/Piton/uchoba/module_12_4/test_12_4.py", line 30, in test_run
    runner = Runner(123)
  File "/home/sergey/Документы/Piton/uchoba/module_12_4/run_tournament.py", line 6, in __init__
    raise TypeError(
TypeError: Имя может быть только строкой, передано int
2024-12-14 15:23:00,107 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "/home/sergey/Документы/Piton/uchoba/module_12_4/test_12_4.py", line 20, in test_walk
    runner = Runner("Bolt", -5)
  File "/home/sergey/Документы/Piton/uchoba/module_12_4/run_tournament.py", line 13, in __init__
    raise ValueError(f"Скорость не может быть отрицательной, сейчас {speed}")
ValueError: Скорость не может быть отрицательной, сейчас -5
